name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Сканирование исходного кода на уязвимости (SAST)
      - name: Run Trivy vulnerability scanner (Repository)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Сборка локального образа для проверки
      - name: Build local Docker image
        run: docker build -t secure-app:test .

      # Сканирование Docker-образа на уязвимости
      - name: Run Trivy vulnerability scanner (Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-app:test'
          image-type: 'image'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

          # Авторизация в GitHub Container Registry с использованием встроенного токена
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Сборка и безопасная публикация
      # 1. Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Переводим имя репозитория в нижний регистр и сохраняем в переменную окружения IMAGE_NAME
      - name: Downcase repository name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 3. Безопасный вход в GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Финальная сборка и отправка с использованием приведенного к нижнему регистру имени
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Используем подстановку переменной env.IMAGE_NAME вместо github.repository
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}/secure-web-app:latest